export const BASE_URL = "http://localhost:8000/";
// export const BASE_URL = "http://13.59.245.234:8000/";

// Endpoints
export const ENDPOINTS = {
  LOGIN: "user/login",
  ALL_USERS: "user/all",
  CHANGE_PASSWORD: "user/change-password",
  DELETE_USER: "user/delete/",
  ADD_PROPERTY: "property/upload",
  ALL_PROPERTIES: "property",
  DELETE_PROPERTY: "property",
  EDIT_PROPERTY: "property/update",
  GET_ALL_INVOICES: "property/getAll",
  UPDATE_PROPERTY: "property/updatePropertyApproval",
  GET_ALL_TIMELINES: "timeline",
  GET_ALL_CATEGORIES: "category",
  POST_ALL_CATEGORIES: "category",
  DELETE_CATEGORY: "category",
  GET_PROPERTY_DETAIL: "property/get-property-detail",
  GET_CHAT_LIST: "singleChat/get-chatlist",
  GET_ALL_CHAT: "singleChat/all-chat",
  GET_ALL_GROUP_CHAT: "group/all-group-chats",
  GET_TIMELINE_BY_ID: "timeline/get-timeline-byid",
  GET_ALL_PROPERTY_TAGS: "tag",
  POST_ALL_TAGS: "tag",
  DELETE_TAG: "tag",
  IS_VERIFIED_USER: "user/verification",
  IS_VISIBLE_TIMELINE: "timeline/visible",
  GET_CHAT_BY_ID_USERS: "singleChat/getChatIdByUsers",
  GET_INVOICES_BY_ID: "property/get-invoice",
  TOGGLE_FOLLOW: "follow",
  GET_ALL_TICKETS: "ticket",
  PUT_RESPONSE: "ticket",
  APPROVE_VERIFICATION_REQUESTS: "verifications",
  GET_ALL_VERIFICATION_REQUESTS: "verifications",
  GET_ALL_USERS_NOTIFICATIONS: "notification/allNotification",
};
